"""
    SPDX-FileCopyrightText: Copyright 2022-2025 Julian Amann <dev@vertexwahn.de>
    SPDX-License-Identifier: Apache-2.0
"""

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")


cc_library(
    name = "normal_integrator",
    srcs = ["normal_integrator.cpp"],
    hdrs = ["normal_integrator.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//core:object_factory",
        "//flatland/rendering/integrator",
        "//flatland/rendering/scene",
    ],
)

cc_test(
    name = "normal_integrator_test",
    size = "small",
    srcs = [
        "normal_integrator_test.cpp",
    ],
    data = ["//okapi/scenes"],
    deps = [
        "//flatland/rendering/integrator",
        "//okapi/rendering/scene:load_scene",
        "//okapi/rendering/sensor",
        "@googletest//:gtest_main",
    ],
)

