"""
    SPDX-FileCopyrightText: Copyright 2024-2026 Julian Amann <dev@vertexwahn.de>
    SPDX-License-Identifier: Apache-2.0
"""

"""okapi build and test dependencies."""

module(
    name = "de_vertexwahn",
    version = "0.0.0",
    compatibility_level = 1,
)

# Depend on apple_support first and then rules_cc so that the Xcode toolchain
# from apple_support wins over the generic Unix toolchain from rules_cc.
bazel_dep(name = "apple_support", version = "2.3.0")

#-------------------------------------------------------------------------------------
# rules_ispc
#-------------------------------------------------------------------------------------

bazel_dep(name = "rules_ispc")
local_path_override(
    module_name = "rules_ispc",
    path = "bazel/rules/rules_ispc",
)

ispc = use_extension("@rules_ispc//:extensions.bzl", "ispc")

# on Windows there are some errors with 1.28.2 - there seem to be some things that are not supported by ISPC + VS2022
# maybe test 1.24.0, etc. to find out when things break and why
#ispc.download(version = "1.28.2")
ispc.download(version = "1.23.0")
use_repo(
    ispc,
    "ispc_linux_x86_64",
    "ispc_osx_arm64",
    "ispc_osx_x86_64",
    "ispc_windows_x86_64",
)

register_toolchains(
    "@rules_ispc//tools:all",
    dev_dependency = True,
)

#-------------------------------------------------------------------------------------
# rules_qt
#-------------------------------------------------------------------------------------

bazel_dep(name = "rules_qt")
#git_override(
#    module_name = "rules_qt",
#    commit = "83c972bc424d9647cbdd6e3a0287c173f2a98576",
#    remote = "https://github.com/Vertexwahn/rules_qt6.git",
#)

local_path_override(
    module_name = "rules_qt",
    path = "bazel/rules/rules_qt6",
)

qt = use_extension("@rules_qt//extension:qt.bzl", "fetch")
qt.install(
    name = "qt_linux_x86_64",
    build_file = "@rules_qt//extension:qt/6.8.3/linux_x86_64.BUILD",
    os = "linux",
    version = "6.8.3",
)
qt.install(
    name = "qt_windows_x86_64",
    build_file = "@rules_qt//extension:qt/6.8.3/windows_x86_64.BUILD",
    os = "windows",
    version = "6.8.3",
    windows_architecture = "win64_msvc2022",
)
qt.install(
    name = "qt_mac_aarch64",
    build_file = "@rules_qt//extension:qt/6.8.3/mac_aarch64.BUILD",
    os = "macos",
    version = "6.8.3",
)
use_repo(qt, "qt_linux_x86_64", "qt_mac_aarch64", "qt_windows_x86_64")

register_toolchains(
    "@rules_qt//tools:all",
)

#-------------------------------------------------------------------------------------

bazel_dep(name = "rules_cuda", version = "0.3.0")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "nasm", version = "2.16.03.bcr.2")

# C++ third party libraries dependencies
bazel_dep(name = "abseil-cpp", version = "20260107.1")
bazel_dep(name = "boost.algorithm", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.asio", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.beast", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.core", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.endian", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.predef", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.program_options", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.uuid", version = "1.90.0.bcr.1")
bazel_dep(name = "cpuinfo", version = "0.0.0-20250925-877328f")
bazel_dep(name = "eigen", version = "5.0.1.bcr.1")
bazel_dep(name = "embree", version = "4.3.1")
bazel_dep(name = "flip", version = "1.6")
bazel_dep(name = "fmt", version = "12.1.0")
bazel_dep(name = "giflib", version = "5.2.1.bcr.1")
bazel_dep(name = "glog", version = "0.7.1.bcr.1")
bazel_dep(name = "hypothesis", version = "0.0.0-20240425-3acfea6.bcr.1")
bazel_dep(name = "imath", version = "3.2.2.bcr.1")
bazel_dep(name = "libdeflate", version = "1.25")
bazel_dep(name = "libjpeg_turbo", version = "3.1.3.bcr.2")  # Version 2.1.91 does not compile on windows, does not uses nasm to build
bazel_dep(name = "libpng", version = "1.6.54")
bazel_dep(name = "libtiff", version = "4.7.1")
bazel_dep(name = "libwebp", version = "1.6.0")
bazel_dep(name = "miniply", version = "0.0.0-20220915-1a235c7")
bazel_dep(name = "nanobind_bazel", version = "2.10.2")
bazel_dep(name = "nlohmann_json", version = "3.12.0.bcr.1")
bazel_dep(name = "onetbb", version = "2022.2.0")
bazel_dep(name = "openexr", version = "3.4.5")
bazel_dep(name = "pcg", version = "0.98.1.bcr.1")
bazel_dep(name = "pugixml", version = "1.15")
bazel_dep(name = "rply", version = "1.1.4")
bazel_dep(name = "spdlog", version = "1.17.0")
bazel_dep(name = "tinyobjloader", version = "2.0.0-rc1.bcr.2")
bazel_dep(name = "tinyply", version = "3.0")
bazel_dep(name = "xtensor", version = "0.27.1")
bazel_dep(name = "xtl", version = "0.8.1")
bazel_dep(name = "yaml-cpp", version = "0.9.0")
bazel_dep(name = "zlib", version = "1.3.2")

bazel_dep(name = "catch2", version = "3.13.0", dev_dependency = True)
bazel_dep(name = "google_benchmark", version = "1.9.5", dev_dependency = True)
bazel_dep(name = "googletest", version = "1.17.0.bcr.2", dev_dependency = True)

bazel_dep(name = "onednn", version = "2.7.3")
local_path_override(
    module_name = "onednn",
    path = "../third_party/oneDNN-2.7.3",
)

include("//bazel/module/go:Go.MODULE.bazel")

include("//bazel/module/java:Java.MODULE.bazel")

include("//bazel/module/tools:Tools.MODULE.bazel")

local_path_override(
    module_name = "bazel_iwyu",
    path = "../third_party/bazel_iwyu-85cbd99369a3ed3f8c31234d2d887026f3e66bbc",
)

# This projects intends to stay as close as possible to upstream dependencies (Live at Head). Therefore, upstream
# dependencies are copied on a regular basis 1:1 with some Bazel related patches (if needed) to the `third_party` folder
# and overridden here. If you do not like this approach you can simply remove most of the local_path_override's here and
# live with the newest versions in the BCR (which can be much older).
# Note: Some dependencies are not part in the BCR and therefore a local_path_override might be needed
# here for some libraries.

# Test abseil-cpp from BCR
#local_path_override(
#    module_name = "abseil-cpp",
#    path = "../third_party/abseil-cpp",
#)

local_path_override(
    module_name = "bazel_skylib",
    path = "../third_party/bazel-skylib",
)

local_path_override(
    module_name = "cpuinfo",
    path = "../third_party/cpuinfo",
)

# Seems not to be needed anymore
#bazel_dep(name = "delaunator-cpp", version = "0.0.0-20181007-c1521f6")
#local_path_override(
#    module_name = "delaunator-cpp",
#    path = "../third_party/delaunator-cpp-c1521f6e879881232dcddabd6c2ddb6187e8714b",
#)

local_path_override(
    module_name = "eigen",
    path = "../third_party/eigen-5.0.1",
)

local_path_override(
    module_name = "flip",
    path = "../third_party/flip-1.6",
)

local_path_override(
    module_name = "fmt",
    path = "../third_party/fmt",
)

local_path_override(
    module_name = "imath",
    path = "../third_party/Imath",
)

local_path_override(
    module_name = "hypothesis",
    path = "../third_party/hypothesis",
)

local_path_override(
    module_name = "libdeflate",
    path = "../third_party/libdeflate-1.24",
)

local_path_override(
    module_name = "libpng",
    path = "../third_party/libpng-1.6.50",
)

local_path_override(
    module_name = "libwebp",
    path = "../third_party/libwebp-1.6.0",
)

#local_path_override(
#    module_name = "nasm",
#    path = "../third_party/nasm-2.14.02",
#)

local_path_override(
    module_name = "onetbb",
    path = "../third_party/oneTBB-2022.2.0",
)

local_path_override(
    module_name = "pcg",
    path = "../third_party/pcg-cpp",
)

local_path_override(
    module_name = "pugixml",
    path = "../third_party/pugixml",
)

local_path_override(
    module_name = "rules_pkg",
    path = "../third_party/rules_pkg-1.1.0",
)

local_path_override(
    module_name = "spdlog",
    path = "../third_party/spdlog",
)

local_path_override(
    module_name = "tinyobjloader",
    path = "../third_party/tinyobjloader",
)

#local_path_override(
#    module_name = "xtensor",
#    path = "../third_party/xtensor",
#)

local_path_override(
    module_name = "xtl",
    path = "../third_party/xtl",
)

local_path_override(
    module_name = "yaml-cpp",
    path = "../third_party/yaml-cpp",
)

local_path_override(
    module_name = "catch2",
    path = "../third_party/Catch2",
)

local_path_override(
    module_name = "googletest",
    path = "../third_party/googletest",
)

bazel_dep(name = "oidn-weights", version = "0.0.0-20210406-a34b764")
local_path_override(
    module_name = "oidn-weights",
    path = "../third_party/oidn-weights-0.0.0-20210406-a34b764",
)

bazel_dep(name = "oidn", version = "1.4.3")
local_path_override(
    module_name = "oidn",
    path = "../third_party/oidn-1.4.3",
)

#-------------------------------------------------------------------------------------
# Windows Resource files
#-------------------------------------------------------------------------------------

winsdk_configure = use_repo_rule("//okapi/res:winsdk_configure.bzl", "winsdk_configure")

winsdk_configure(name = "local_config_winsdk")

register_toolchains("@local_config_winsdk//:all")

register_toolchains("//okapi/res:empty_rc_toolchain")

include("//bazel/module/cpp:Cpp.MODULE.bazel")

#-------------------------------------------------------------------------------------
# Python
#-------------------------------------------------------------------------------------

include("//bazel/module/python:Python.MODULE.bazel")

include("//bazel/module/oci:Oci.MODULE.bazel")

#-------------------------------------------------------------------------------------
# Doxygen

doxygen_extension = use_extension("@rules_doxygen//:extensions.bzl", "doxygen_extension")
use_repo(doxygen_extension, "doxygen")

#-------------------------------------------------------------------------------------
