version = 1

[[annotations]]
path = "okapi/ui/widgets/*"
SPDX-FileCopyrightText = "2024 Jane Doe <jane@example.com>"
SPDX-FileCopyrightText = "2010-2013 Francois Beaune, Jupiter Jazz Limited"
SPDX-FileCopyrightText = "2014-2019 Francois Beaune, The appleseedhq Organization"
SPDX-License-Identifier = "MIT"
