"""
    SPDX-FileCopyrightText: Copyright 2022-2023 Julian Amann <dev@vertexwahn.de>
    SPDX-License-Identifier: Apache-2.0
"""

package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "scenes",
    srcs = [
        "cube/cube.normal.okapi.xml",
        "cube/cube.obj",
        "sphere/sphere.normal.okapi.xml",
    ],
)

