"""
    SPDX-FileCopyrightText: Copyright 2022-2026 Julian Amann <dev@vertexwahn.de>
    SPDX-License-Identifier: Apache-2.0
"""

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "load_scene",
    srcs = ["load_scene.cpp"],
    hdrs = ["load_scene.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":registry",
        "//core:exception",
        "//core:object_factory",
        "//flatland/rendering/canvas:svg_canvas",
        "//flatland/rendering/scene",
        "//flatland/rendering/scene:load_scene",
        "//okapi/rendering/reconstruction_filter",
        "//okapi/rendering/sensor",
        "//okapi/rendering/sensor:film",
    ],
)


cc_library(
    name = "registry",
    srcs = ["registry.cpp"],
    hdrs = ["registry.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//core:namespace",
        "//flatland/rendering:sampler",
        "//flatland/rendering/intersector:brute_force_intersector",
        "//okapi/rendering/bsdf:diffuse",
        "//okapi/rendering/integrator:normal_integrator",
        "//okapi/rendering/intersector:embree_intersector",
        "//okapi/rendering/reconstruction_filter",
        "//okapi/rendering/shape:serialzied_mesh",
        "//okapi/rendering/shape:sphere",
        "//okapi/rendering/shape:triangle_mesh",
        "//okapi/rendering/texture:alpha_blended_texture",
        "//okapi/rendering/texture:bitmap",
        "//okapi/rendering/texture:checkerboard",
    ],
)
