"""
    SPDX-FileCopyrightText: Copyright 2026 Julian Amann <dev@vertexwahn.de>
    SPDX-License-Identifier: Apache-2.0
"""

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")


cc_library(
    name = "reconstruction_filter",
    srcs = ["reconstruction_filter.cpp"],
    hdrs = ["reconstruction_filter.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//core:object",
        "//core:object_factory",
        "//flatland/rendering:property_set",
        "//math:constants",
        "//math:util",
    ],
)

cc_test(
    name = "reconstruction_filter_test",
    size = "small",
    srcs = [
        "reconstruction_filter_test.cpp",
    ],
    data = [
        "//okapi/tests/images:filtered_images",
    ],
    deps = [
        ":reconstruction_filter",
        "//imaging/io",
        "@googletest//:gtest_main",
    ],
)
